[tool.poetry]
name = "speechflow"
version = "0.1.0"
description = ""
authors = ["mfenerich <marcel@feneri.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
